M48
; DRILL file {KiCad 9.0.7} date 2026-04-06T17:05:36-0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-06T17:05:36-09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X147.805Y-104.43
X147.805Y-110.21
T2
X112.5Y-125.5
X119.5Y-125.5
M30
