M48
; DRILL file {KiCad 9.0.7} date 2026-04-09T16:31:51+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-09T16:31:51+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X164.32Y-141.93
X164.32Y-147.71
T2
X133.0Y-145.581
X140.0Y-145.581
M30
